mdns: remove unused enum
If header is included multiple times:

```
/home/builder/.platformio/packages/framework-arduinoespressif8266@src-31d658a59f41540201fc3726a1394910/libraries/ESP8266mDNS/src/ESP8266mDNS.h:45:12: error: multiple definition of 'enum class MDNSApiVersion'
   45 | enum class MDNSApiVersion { LEA, LEAv2 };
      |            ^~~~~~~~~~~~~~
In file included from espurna/mdns.h:8,
                 from espurna/main.cpp:41,
                 from espurna/espurna_single_source.cpp:23:
/home/builder/.platformio/packages/framework-arduinoespressif8266@src-31d658a59f41540201fc3726a1394910/libraries/ESP8266mDNS/src/ESP8266mDNS.h:45:12: note: previous definition here
   45 | enum class MDNSApiVersion { LEA, LEAv2 };
      |            ^~~~~~~~~~~~~~
```

I can't find any usage, so just removing the enum fixes the issue.

Preventive fix with `#pragma once` in case this comes back.
Although, I am not seeing it being used anywhere else. Is the `#ifndef THIS_HEADER #define THIS_HEADER ... #endif` guard the preferred method?